#!/bin/bash
# Copyright 2024 Figure AI, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Usage: bazel run //:generate_compile_commands -- <build_targets>

set -euo pipefail

# --- begin runfiles.bash initialization ---
# Copy-pasted from Bazel's Bash runfiles library (tools/bash/runfiles/runfiles.bash).
if [[ ! -d "${RUNFILES_DIR:-/dev/null}" && ! -f "${RUNFILES_MANIFEST_FILE:-/dev/null}" ]]; then
    if [[ -f "$0.runfiles_manifest" ]]; then
        export RUNFILES_MANIFEST_FILE="$0.runfiles_manifest"
    elif [[ -f "$0.runfiles/MANIFEST" ]]; then
        export RUNFILES_MANIFEST_FILE="$0.runfiles/MANIFEST"
    elif [[ -f "$0.runfiles/bazel_tools/tools/bash/runfiles/runfiles.bash" ]]; then
        export RUNFILES_DIR="$0.runfiles"
    fi
fi
if [[ -f "${RUNFILES_DIR:-/dev/null}/bazel_tools/tools/bash/runfiles/runfiles.bash" ]]; then
    source "${RUNFILES_DIR}/bazel_tools/tools/bash/runfiles/runfiles.bash"
elif [[ -f "${RUNFILES_MANIFEST_FILE:-/dev/null}" ]]; then
    source "$(grep -m1 "^bazel_tools/tools/bash/runfiles/runfiles.bash " "$RUNFILES_MANIFEST_FILE" | cut -d ' ' -f 2-)"
else
    echo >&2 "ERROR: cannot find @bazel_tools//tools/bash/runfiles:runfiles.bash"
    exit 1
fi
# --- end runfiles.bash initialization ---

extra_flags=""
while getopts "c:o:" opt; do
    case "${opt}" in
    c)
        extra_flags="--config=${OPTARG}"
        ;;
    o)
        output_file="${OPTARG}"
        ;;
    *)
        echo "Invalid option: ${opt}"
        exit 1
        ;;
    esac
done
shift $((OPTIND - 1))

build_targets=("$@")
if [ ${#build_targets[@]} -eq 0 ]; then
    echo "No build targets provided." >&2
    exit 1
fi

MERGE_COMMANDS_BINARY=$(rlocation bazel_clangd_helper/merge_compile_commands)
if [ -z "${MERGE_COMMANDS_BINARY}" ]; then
    echo "Could not find merge_compile_commands binary." >&2
    exit 1
fi

# When running from a sh_binary, the workspace dir is a directory in bazel-out.
# `bazel info workspace` cannot be called from here so find the actual directory.
if [ -n "${BUILD_WORKSPACE_DIRECTORY}" ]; then
    workspace_dir="${BUILD_WORKSPACE_DIRECTORY}"
else
    workspace_dir="$(bazel info workspace)"
fi
echo "Running from workspace directory: ${workspace_dir}"
cd "${workspace_dir}"

events_file=$(mktemp)

bazel build ${extra_flags:+"$extra_flags"} \
    --aspects=@bazel_clangd_helper//:build_defs.bzl%compile_commands_aspect \
    --output_groups=report \
    --build_event_json_file="${events_file}" \
    "${build_targets[@]}"

bazel_bin_dir="$(bazel info ${extra_flags:+"$extra_flags"} bazel-bin)"
echo "Looking in bazel-bin directory: ${bazel_bin_dir}"

output_file=${output_file:-"${workspace_dir}/compile_commands.json"}

"${MERGE_COMMANDS_BINARY}" \
    --workspace_dir="${workspace_dir}" \
    --compile_commands_path="${output_file}" \
    --build_event_path="${events_file}"

# Create the external symlink if not present already.
if [ ! -e "${workspace_dir}/external" ]; then
    ln -s "bazel-out/../../../external" "${workspace_dir}/external"
fi

# Update the local git exclude file if the line isn't present.
GITIGNORE_LINES=(
    "### Autogenerated by bazel_clangd_helper."
    "/external"
    "/compile_commands.json"
    ".cache/"
)
for line in "${GITIGNORE_LINES[@]}"; do
    if ! grep -q "${line}" "${workspace_dir}/.git/info/exclude"; then
        echo "${line}" >>"${workspace_dir}/.git/info/exclude"
    fi
done

rm -f "${events_file}"
